services:
  dev:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./lib
          target: /home/flutteruser/app/lib
        - action: rebuild
          path: ./pubspec.yaml
        - action: rebuild
          path: ./pubspec.lock
